# Generated by Django 5.2.17 on 2026-09-25 18:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models

import ligacoes.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_import_run"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="relationship",
            name="kind",
            field=models.CharField(
                choices=[
                    ("employment", "Emprego"),
                    ("directorship", "Administração"),
                    ("shareholding", "Participação societária"),
                    ("membership", "Filiação"),
                    ("education", "Formação"),
                    ("family", "Relação familiar"),
                    ("public_office", "Cargo público"),
                    ("professional_activity", "Atividade profissional"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="SourceApproval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                        ],
                        max_length=16,
                        unique=True,
                        verbose_name="origem",
                    ),
                ),
                (
                    "purpose",
                    models.TextField(
                        max_length=2000, verbose_name="finalidade de interesse público"
                    ),
                ),
                (
                    "reuse_basis",
                    models.TextField(
                        max_length=2000,
                        verbose_name="referência de autorização de reutilização ou base legal",
                    ),
                ),
                ("allowed_scopes", models.JSONField(verbose_name="categorias autorizadas")),
                (
                    "retention_conditions",
                    models.TextField(
                        max_length=2000, verbose_name="condições de conservação e revisão"
                    ),
                ),
                ("review_due_at", models.DateTimeField(verbose_name="rever autorização até")),
                (
                    "approved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="autorizado em"
                    ),
                ),
                ("is_active", models.BooleanField(default=False, verbose_name="autorização ativa")),
                (
                    "approved_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="autorizado por",
                    ),
                ),
            ],
            options={
                "verbose_name": "autorização de recolha",
                "verbose_name_plural": "autorizações de recolha",
                "permissions": [
                    ("approve_sourceapproval", "Pode autorizar recolha de fontes externas")
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceIdentity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                        ],
                        max_length=16,
                        verbose_name="origem",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=240, verbose_name="identificador oficial"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="identidade revista em"
                    ),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="fundamento da correspondência"
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(
                        blank=True, editable=False, null=True, verbose_name="primeira utilização"
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.entity",
                        verbose_name="entidade verificada",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="identidade revista por",
                    ),
                ),
            ],
            options={
                "verbose_name": "correspondência de identidade",
                "verbose_name_plural": "correspondências de identidade",
                "permissions": [
                    ("review_sourceidentity", "Pode rever correspondências de identidade")
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceObservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                        ],
                        max_length=16,
                        verbose_name="origem",
                    ),
                ),
                ("scope", models.CharField(max_length=240, verbose_name="âmbito da observação")),
                (
                    "external_id",
                    models.CharField(max_length=240, verbose_name="identificador da passagem"),
                ),
                ("revision", models.CharField(max_length=128, verbose_name="revisão da fonte")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("government_office", "Cargo governamental"),
                            ("biography_role", "Passagem profissional biográfica"),
                            ("declared_interest", "Interesse ou atividade profissional declarada"),
                        ],
                        max_length=24,
                        verbose_name="categoria",
                    ),
                ),
                ("passage", models.TextField(max_length=10000, verbose_name="passagem mínima")),
                (
                    "source_url",
                    models.URLField(
                        max_length=2048,
                        validators=[ligacoes.core.validators.validate_source_url],
                        verbose_name="URL da fonte",
                    ),
                ),
                ("publisher", models.CharField(max_length=240, verbose_name="editor da fonte")),
                (
                    "reference",
                    models.CharField(max_length=160, verbose_name="referência da passagem"),
                ),
                ("title", models.CharField(max_length=300, verbose_name="título da fonte")),
                (
                    "effective_start",
                    models.DateField(
                        blank=True, null=True, verbose_name="início indicado pela fonte"
                    ),
                ),
                (
                    "effective_end",
                    models.DateField(blank=True, null=True, verbose_name="fim indicado pela fonte"),
                ),
                (
                    "declared_on",
                    models.DateField(
                        blank=True, null=True, verbose_name="data da declaração, não da atividade"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("employment", "Emprego"),
                            ("directorship", "Administração"),
                            ("shareholding", "Participação societária"),
                            ("membership", "Filiação"),
                            ("education", "Formação"),
                            ("family", "Relação familiar"),
                            ("public_office", "Cargo público"),
                            ("professional_activity", "Atividade profissional"),
                        ],
                        max_length=24,
                        verbose_name="tipo indicado pela fonte",
                    ),
                ),
                ("as_of", models.DateField(verbose_name="última data de referência")),
                (
                    "retrieved_at",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="recolhida em"
                    ),
                ),
                (
                    "is_current",
                    models.BooleanField(default=True, verbose_name="presente na última observação"),
                ),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="convertida em"),
                ),
                (
                    "review_notes",
                    models.TextField(
                        blank=True, max_length=2000, verbose_name="fundamento editorial"
                    ),
                ),
                (
                    "evidence",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.evidence",
                        verbose_name="evidência editorial",
                    ),
                ),
                (
                    "identity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="observations",
                        to="core.sourceidentity",
                        verbose_name="identidade oficial",
                    ),
                ),
                (
                    "object",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.entity",
                        verbose_name="organização identificada pela fonte",
                    ),
                ),
                (
                    "relationship",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="core.relationship",
                        verbose_name="relação editorial",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="convertida por",
                    ),
                ),
            ],
            options={
                "verbose_name": "candidata de enriquecimento",
                "verbose_name_plural": "candidatas de enriquecimento",
                "ordering": ["-as_of", "pk"],
                "permissions": [
                    (
                        "review_sourceobservation",
                        "Pode converter candidatas em relações de rascunho",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SourceSyncState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                        ],
                        max_length=16,
                    ),
                ),
                ("scope", models.CharField(max_length=240)),
                ("as_of", models.DateField()),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "scope"), name="source_sync_scope_unique"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="sourceidentity",
            constraint=models.UniqueConstraint(
                fields=("source", "external_id"), name="source_identity_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobservation",
            constraint=models.UniqueConstraint(
                fields=("source", "scope", "external_id", "revision"),
                name="source_observation_revision",
            ),
        ),
        migrations.AddConstraint(
            model_name="sourceobservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_current", True)),
                fields=("source", "scope", "external_id"),
                name="source_observation_current",
            ),
        ),
    ]
