# Generated by Django 5.2.17 on 2026-09-27 23:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_source_enrichment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sourceapproval",
            name="approved_by",
        ),
        migrations.RemoveConstraint(
            model_name="relationship",
            name="published_relationship_reviewed",
        ),
        migrations.AlterField(
            model_name="importrun",
            name="mode",
            field=models.CharField(
                choices=[("dry_run", "Validar sem aplicar"), ("apply", "Aplicar e publicar")],
                default="dry_run",
                max_length=8,
                verbose_name="modo",
            ),
        ),
        migrations.AlterField(
            model_name="reviewevent",
            name="action",
            field=models.CharField(
                choices=[
                    ("publish", "Publicação"),
                    ("auto_publish", "Publicação automática"),
                    ("withdraw", "Publicação retirada"),
                    ("invalidate", "Revisão invalidada"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="relationship",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "published"), _negated=True),
                    ("reviewed_at__isnull", False),
                    _connector="OR",
                ),
                name="published_relationship_reviewed",
            ),
        ),
        migrations.DeleteModel(
            name="SourceApproval",
        ),
    ]
