# Generated by Django 5.2.17 on 2026-09-28 19:09

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import ligacoes.core.validators


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_readable_parliament_excerpts"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "dataset",
                    models.CharField(
                        db_index=True, max_length=64, verbose_name="conjunto de dados"
                    ),
                ),
                ("scope", models.CharField(max_length=64, verbose_name="âmbito")),
                (
                    "record_id",
                    models.CharField(max_length=240, verbose_name="identificador do registo"),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato público"),
                            ("subsidy", "Apoio público"),
                            ("eu_funding", "Fundos europeus"),
                            ("meeting", "Reunião"),
                            ("hearing", "Audição ou audiência parlamentar"),
                            ("gift", "Oferta"),
                            ("hospitality", "Hospitalidade"),
                            ("travel", "Deslocação"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("title", models.CharField(max_length=500, verbose_name="título")),
                ("date", models.DateField(blank=True, null=True, verbose_name="data")),
                ("start_date", models.DateField(blank=True, null=True, verbose_name="início")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="fim")),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=18,
                        null=True,
                        verbose_name="montante",
                    ),
                ),
                ("currency", models.CharField(default="EUR", max_length=3, verbose_name="moeda")),
                (
                    "amount_label",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="designação do montante"
                    ),
                ),
                (
                    "record_url",
                    models.URLField(
                        blank=True,
                        max_length=2048,
                        validators=[ligacoes.core.validators.validate_source_url],
                        verbose_name="URL do registo",
                    ),
                ),
                ("details", models.JSONField(blank=True, default=dict, verbose_name="detalhes")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Rascunho"),
                            ("published", "Publicado"),
                            ("ceased", "Ausente da fonte"),
                            ("withdrawn", "Retirado"),
                        ],
                        default="draft",
                        max_length=10,
                        verbose_name="estado",
                    ),
                ),
                ("fingerprint", models.CharField(max_length=64, verbose_name="impressão digital")),
                ("as_of", models.DateField(verbose_name="última data de referência")),
                ("retrieved_at", models.DateTimeField(verbose_name="recolhido em")),
                (
                    "published_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="publicado em"),
                ),
                (
                    "withdrawn_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="retirado em"),
                ),
            ],
            options={
                "verbose_name": "evento",
                "verbose_name_plural": "eventos",
                "ordering": ["-date", "pk"],
                "permissions": [("withdraw_event", "Pode retirar eventos publicados")],
            },
        ),
        migrations.CreateModel(
            name="EventParty",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("buyer", "Entidade adjudicante"),
                            ("supplier", "Adjudicatário"),
                            ("bidder", "Concorrente"),
                            ("grantor", "Entidade concedente"),
                            ("beneficiary", "Beneficiário"),
                            ("intermediary", "Intermediário"),
                            ("attendee", "Participante"),
                            ("host", "Órgão ou anfitrião"),
                            ("provider", "Ofertante"),
                            ("recipient", "Destinatário"),
                        ],
                        max_length=16,
                        verbose_name="papel",
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="nome como publicado")),
                (
                    "identifier",
                    models.CharField(
                        blank=True, max_length=80, verbose_name="identificador na fonte"
                    ),
                ),
            ],
            options={
                "verbose_name": "interveniente em evento",
                "verbose_name_plural": "intervenientes em eventos",
                "ordering": ["pk"],
            },
        ),
        migrations.CreateModel(
            name="IdentitySuggestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                            ("sioe", "SIOE+"),
                            ("ep", "Parlamento Europeu"),
                            ("nipc", "NIPC"),
                            ("lei", "LEI (GLEIF)"),
                            ("eu_tr", "Registo de Transparência da UE"),
                            ("wikidata", "Wikidata (pista)"),
                        ],
                        max_length=16,
                        verbose_name="esquema",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=240, verbose_name="identificador oficial"),
                ),
                (
                    "name_as_published",
                    models.CharField(max_length=300, verbose_name="nome publicado pela fonte"),
                ),
                ("basis", models.TextField(max_length=2000, verbose_name="fundamento da sugestão")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pendente"),
                            ("accepted", "Aceite"),
                            ("rejected", "Rejeitada"),
                        ],
                        default="pending",
                        max_length=8,
                        verbose_name="estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="sugerida em")),
                (
                    "reviewed_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="revista em"),
                ),
            ],
            options={
                "verbose_name": "sugestão de identidade",
                "verbose_name_plural": "sugestões de identidade",
                "ordering": ["status", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Term",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("legislature", "Legislatura"),
                            ("government", "Governo"),
                            ("ep_term", "Legislatura europeia"),
                        ],
                        max_length=16,
                        verbose_name="tipo",
                    ),
                ),
                ("code", models.CharField(max_length=24, verbose_name="código")),
                ("label", models.CharField(max_length=160, verbose_name="designação")),
                ("start_date", models.DateField(verbose_name="início")),
                ("end_date", models.DateField(blank=True, null=True, verbose_name="fim")),
            ],
            options={
                "verbose_name": "mandato",
                "verbose_name_plural": "mandatos",
                "ordering": ["kind", "start_date"],
            },
        ),
        migrations.AddField(
            model_name="entity",
            name="classification",
            field=models.CharField(
                blank=True,
                choices=[
                    ("parliament", "Parlamento"),
                    ("parliamentary_group", "Grupo parlamentar"),
                    ("parliamentary_committee", "Comissão parlamentar"),
                    ("parliamentary_body", "Órgão parlamentar"),
                    ("parliamentary_delegation", "Delegação parlamentar"),
                    ("friendship_group", "Grupo parlamentar de amizade"),
                    ("government", "Governo"),
                    ("government_department", "Área governativa"),
                    ("government_office", "Gabinete governamental"),
                    ("public_body", "Organismo público"),
                    ("regulator", "Entidade reguladora"),
                    ("state_company", "Empresa pública"),
                    ("municipality", "Município"),
                    ("parish", "Freguesia"),
                    ("eu_institution", "Instituição europeia"),
                    ("company", "Empresa"),
                    ("foundation", "Fundação"),
                    ("association", "Associação"),
                    ("cooperative", "Cooperativa"),
                    ("higher_education", "Ensino superior"),
                    ("international_organisation", "Organização internacional"),
                    ("other", "Outra"),
                ],
                max_length=32,
                verbose_name="classificação",
            ),
        ),
        migrations.AddField(
            model_name="entity",
            name="dissolution_date",
            field=models.DateField(blank=True, null=True, verbose_name="data de extinção"),
        ),
        migrations.AddField(
            model_name="entity",
            name="founding_date",
            field=models.DateField(blank=True, null=True, verbose_name="data de fundação"),
        ),
        migrations.AddField(
            model_name="relationship",
            name="end_precision",
            field=models.CharField(
                choices=[("day", "Dia"), ("month", "Mês"), ("year", "Ano")],
                default="day",
                max_length=5,
                verbose_name="precisão da data final",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="role",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="cargo ou função (fonte)"
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="role_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leadership", "Presidência ou direção"),
                    ("deputy_leadership", "Vice-presidência ou coordenação"),
                    ("member", "Membro"),
                    ("substitute", "Suplente"),
                    ("staff", "Gabinete ou apoio"),
                    ("other", "Outra função"),
                ],
                max_length=24,
                verbose_name="classe da função",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="start_precision",
            field=models.CharField(
                choices=[("day", "Dia"), ("month", "Mês"), ("year", "Ano")],
                default="day",
                max_length=5,
                verbose_name="precisão da data inicial",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="temporal_status",
            field=models.CharField(
                choices=[
                    ("current", "Em curso"),
                    ("ended", "Terminada"),
                    ("unknown", "Desconhecida"),
                ],
                default="unknown",
                max_length=8,
                verbose_name="estado temporal",
            ),
        ),
        migrations.AddField(
            model_name="source",
            name="dataset",
            field=models.CharField(
                blank=True, db_index=True, max_length=64, verbose_name="conjunto de dados"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="dataset",
            field=models.CharField(blank=True, max_length=64, verbose_name="conjunto de dados"),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="end_precision",
            field=models.CharField(
                choices=[("day", "Dia"), ("month", "Mês"), ("year", "Ano")],
                default="day",
                max_length=5,
                verbose_name="precisão do fim",
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="object_identifier",
            field=models.CharField(
                blank=True, max_length=80, verbose_name="identificador da organização na fonte"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="object_name",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="organização como publicada"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="role",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="cargo ou função (fonte)"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="role_class",
            field=models.CharField(
                blank=True,
                choices=[
                    ("leadership", "Presidência ou direção"),
                    ("deputy_leadership", "Vice-presidência ou coordenação"),
                    ("member", "Membro"),
                    ("substitute", "Suplente"),
                    ("staff", "Gabinete ou apoio"),
                    ("other", "Outra função"),
                ],
                max_length=24,
                verbose_name="classe da função",
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="start_precision",
            field=models.CharField(
                choices=[("day", "Dia"), ("month", "Mês"), ("year", "Ano")],
                default="day",
                max_length=5,
                verbose_name="precisão do início",
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="subject_name",
            field=models.CharField(
                blank=True, max_length=300, verbose_name="titular como publicado"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="subject_reference",
            field=models.CharField(
                blank=True, max_length=240, verbose_name="referência oficial do titular"
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="temporal_status",
            field=models.CharField(
                choices=[
                    ("current", "Em curso"),
                    ("ended", "Terminada"),
                    ("unknown", "Desconhecida"),
                ],
                default="unknown",
                max_length=8,
                verbose_name="estado temporal",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="kind",
            field=models.CharField(
                choices=[
                    ("employment", "Emprego"),
                    ("directorship", "Administração"),
                    ("shareholding", "Participação societária"),
                    ("membership", "Filiação"),
                    ("education", "Formação"),
                    ("family", "Relação familiar"),
                    ("public_office", "Cargo público"),
                    ("professional_activity", "Atividade profissional"),
                    ("part_of", "Integra"),
                    ("succession", "Sucede a"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceidentity",
            name="source",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+"),
                    ("ep", "Parlamento Europeu"),
                    ("nipc", "NIPC"),
                    ("lei", "LEI (GLEIF)"),
                    ("eu_tr", "Registo de Transparência da UE"),
                    ("wikidata", "Wikidata (pista)"),
                ],
                max_length=16,
                verbose_name="esquema",
            ),
        ),
        migrations.AlterField(
            model_name="sourceobservation",
            name="category",
            field=models.CharField(
                choices=[
                    ("government_office", "Cargo governamental"),
                    ("biography_role", "Passagem profissional biográfica"),
                    ("declared_interest", "Interesse ou atividade profissional declarada"),
                    ("parliament_body", "Composição de órgão parlamentar"),
                    ("office_holding", "Titularidade de cargo"),
                    ("organisation_structure", "Estrutura organizacional"),
                ],
                max_length=24,
                verbose_name="categoria",
            ),
        ),
        migrations.AlterField(
            model_name="sourceobservation",
            name="identity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="core.sourceidentity",
                verbose_name="identidade oficial",
            ),
        ),
        migrations.AlterField(
            model_name="sourceobservation",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employment", "Emprego"),
                    ("directorship", "Administração"),
                    ("shareholding", "Participação societária"),
                    ("membership", "Filiação"),
                    ("education", "Formação"),
                    ("family", "Relação familiar"),
                    ("public_office", "Cargo público"),
                    ("professional_activity", "Atividade profissional"),
                    ("part_of", "Integra"),
                    ("succession", "Sucede a"),
                ],
                max_length=24,
                verbose_name="tipo indicado pela fonte",
            ),
        ),
        migrations.AlterField(
            model_name="sourceobservation",
            name="source",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+ (DGAEP)"),
                    ("gleif", "GLEIF"),
                    ("ep", "Parlamento Europeu"),
                    ("etf", "Entidade do Tesouro e Finanças"),
                ],
                max_length=16,
                verbose_name="origem",
            ),
        ),
        migrations.AlterField(
            model_name="sourcesyncstate",
            name="source",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+ (DGAEP)"),
                    ("gleif", "GLEIF"),
                    ("ep", "Parlamento Europeu"),
                    ("etf", "Entidade do Tesouro e Finanças"),
                ],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="events",
                to="core.source",
                verbose_name="fonte",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="withdrawn_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="withdrawn_events",
                to=settings.AUTH_USER_MODEL,
                verbose_name="retirado por",
            ),
        ),
        migrations.AddField(
            model_name="eventparty",
            name="entity",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="event_parties",
                to="core.entity",
                verbose_name="entidade",
            ),
        ),
        migrations.AddField(
            model_name="eventparty",
            name="event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="parties",
                to="core.event",
                verbose_name="evento",
            ),
        ),
        migrations.AddField(
            model_name="identitysuggestion",
            name="candidate",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_suggestions",
                to="core.entity",
                verbose_name="entidade candidata",
            ),
        ),
        migrations.AddField(
            model_name="identitysuggestion",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="identity_suggestion_reviews",
                to=settings.AUTH_USER_MODEL,
                verbose_name="revista por",
            ),
        ),
        migrations.AddField(
            model_name="term",
            name="institution",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terms",
                to="core.entity",
                verbose_name="instituição",
            ),
        ),
        migrations.AddField(
            model_name="relationship",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="relationships",
                to="core.term",
                verbose_name="mandato",
            ),
        ),
        migrations.AddField(
            model_name="sourceobservation",
            name="term",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="observations",
                to="core.term",
                verbose_name="mandato",
            ),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["status", "kind"], name="event_status_kind_idx"),
        ),
        migrations.AddIndex(
            model_name="event",
            index=models.Index(fields=["date"], name="event_date_idx"),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.UniqueConstraint(
                fields=("dataset", "record_id"), name="event_record_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__isnull", True), ("amount__gte", 0), _connector="OR"),
                name="event_amount_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_date__isnull", True),
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="event_valid_dates",
            ),
        ),
        migrations.AddConstraint(
            model_name="event",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status", "withdrawn"), ("withdrawn_at__isnull", False)),
                    models.Q(
                        models.Q(("status", "withdrawn"), _negated=True),
                        ("withdrawn_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="event_withdrawal_recorded",
            ),
        ),
        migrations.AddIndex(
            model_name="eventparty",
            index=models.Index(fields=["entity", "event"], name="event_party_entity_idx"),
        ),
        migrations.AddConstraint(
            model_name="eventparty",
            constraint=models.UniqueConstraint(
                fields=("event", "role", "name", "identifier"), name="event_party_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="identitysuggestion",
            constraint=models.UniqueConstraint(
                fields=("scheme", "external_id", "candidate"), name="identity_suggestion_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.UniqueConstraint(
                fields=("kind", "code"), name="term_kind_code_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="term",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("end_date__isnull", True),
                    ("end_date__gte", models.F("start_date")),
                    _connector="OR",
                ),
                name="term_valid_dates",
            ),
        ),
    ]
