# Generated by Django 5.2.17 on 2026-09-28 20:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_government_scopes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitysuggestion",
            name="scheme",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+"),
                    ("ep", "Parlamento Europeu"),
                    ("nipc", "NIPC"),
                    ("lei", "LEI (GLEIF)"),
                    ("eu_tr", "Registo de Transparência da UE"),
                    ("ec", "Comissão Europeia"),
                    ("wikidata", "Wikidata (pista)"),
                ],
                max_length=16,
                verbose_name="esquema",
            ),
        ),
        migrations.AlterField(
            model_name="sourceidentity",
            name="source",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+"),
                    ("ep", "Parlamento Europeu"),
                    ("nipc", "NIPC"),
                    ("lei", "LEI (GLEIF)"),
                    ("eu_tr", "Registo de Transparência da UE"),
                    ("ec", "Comissão Europeia"),
                    ("wikidata", "Wikidata (pista)"),
                ],
                max_length=16,
                verbose_name="esquema",
            ),
        ),
    ]
