# Generated by Django 5.2.17 on 2026-09-29 10:12

import django.db.models.deletion
from django.db import migrations, models


def backfill(apps, schema_editor):
    """Fill the derived tables from the events already stored (no-op on an empty database)."""
    if not apps.get_model("core", "Event").objects.exists():
        return
    from ligacoes.core.event_summaries import rebuild_event_summaries

    with schema_editor.connection.cursor() as cursor:
        cursor.execute("SET LOCAL statement_timeout = 0")
    rebuild_event_summaries()


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_identity_scheme_ec"),
    ]

    operations = [
        migrations.CreateModel(
            name="EventEntitySummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato público"),
                            ("subsidy", "Apoio público"),
                            ("eu_funding", "Fundos europeus"),
                            ("meeting", "Reunião"),
                            ("hearing", "Audição ou audiência parlamentar"),
                            ("gift", "Oferta"),
                            ("hospitality", "Hospitalidade"),
                            ("travel", "Deslocação"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_count", models.PositiveIntegerField()),
                ("amount_eur_sum", models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ("period_start", models.DateField(null=True)),
                ("period_end", models.DateField(null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "kind", "dataset"), name="event_entity_summary_unique"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EventPairSummary",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset", models.CharField(max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("contract", "Contrato público"),
                            ("subsidy", "Apoio público"),
                            ("eu_funding", "Fundos europeus"),
                            ("meeting", "Reunião"),
                            ("hearing", "Audição ou audiência parlamentar"),
                            ("gift", "Oferta"),
                            ("hospitality", "Hospitalidade"),
                            ("travel", "Deslocação"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "entity_role",
                    models.CharField(
                        choices=[
                            ("buyer", "Entidade adjudicante"),
                            ("supplier", "Adjudicatário"),
                            ("bidder", "Concorrente"),
                            ("grantor", "Entidade concedente"),
                            ("beneficiary", "Beneficiário"),
                            ("intermediary", "Intermediário"),
                            ("attendee", "Participante"),
                            ("host", "Órgão ou anfitrião"),
                            ("provider", "Ofertante"),
                            ("recipient", "Destinatário"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "counterpart_role",
                    models.CharField(
                        choices=[
                            ("buyer", "Entidade adjudicante"),
                            ("supplier", "Adjudicatário"),
                            ("bidder", "Concorrente"),
                            ("grantor", "Entidade concedente"),
                            ("beneficiary", "Beneficiário"),
                            ("intermediary", "Intermediário"),
                            ("attendee", "Participante"),
                            ("host", "Órgão ou anfitrião"),
                            ("provider", "Ofertante"),
                            ("recipient", "Destinatário"),
                        ],
                        max_length=16,
                    ),
                ),
                ("event_count", models.PositiveIntegerField()),
                ("amount_eur_sum", models.DecimalField(decimal_places=2, max_digits=22, null=True)),
                ("period_start", models.DateField(null=True)),
                ("period_end", models.DateField(null=True)),
                (
                    "counterpart",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.entity",
                    ),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        db_index=False,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "entity",
                            "kind",
                            "counterpart",
                            "dataset",
                            "entity_role",
                            "counterpart_role",
                        ),
                        name="event_pair_summary_unique",
                    )
                ],
            },
        ),
        migrations.RunPython(backfill, migrations.RunPython.noop),
    ]
