# Generated by Django 5.2.17 on 2026-09-29 10:34

import django.db.models.functions.comparison
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0012_event_summaries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="event",
            index=models.Index(
                models.OrderBy(
                    django.db.models.functions.comparison.Coalesce("date", "start_date"),
                    descending=True,
                    nulls_last=True,
                ),
                models.F("id"),
                condition=models.Q(("status", "published")),
                name="event_listing_idx",
            ),
        ),
    ]
