# Generated by Django 5.2.17 on 2026-10-03 12:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0014_freeze_event_anchors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="identitysuggestion",
            name="scheme",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+"),
                    ("ep", "Parlamento Europeu"),
                    ("nipc", "NIPC"),
                    ("lei", "LEI (GLEIF)"),
                    ("eu_tr", "Registo de Transparência da UE"),
                    ("ec", "Comissão Europeia"),
                    ("wikidata", "Wikidata (pista)"),
                    ("declared_name", "Organização sem identificador (nome declarado)"),
                    ("scoped_name", "Pessoa sem identificador (nome na fonte)"),
                ],
                max_length=16,
                verbose_name="esquema",
            ),
        ),
        migrations.AlterField(
            model_name="relationship",
            name="kind",
            field=models.CharField(
                choices=[
                    ("employment", "Emprego"),
                    ("directorship", "Administração"),
                    ("shareholding", "Participação societária"),
                    ("membership", "Filiação"),
                    ("education", "Formação"),
                    ("family", "Relação familiar"),
                    ("public_office", "Cargo público"),
                    ("professional_activity", "Atividade profissional"),
                    ("part_of", "Integra"),
                    ("succession", "Sucede a"),
                    ("declared_client", "Cliente declarado"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="sourceidentity",
            name="source",
            field=models.CharField(
                choices=[
                    ("government", "Governo"),
                    ("ept", "Entidade para a Transparência"),
                    ("parliament", "Assembleia da República"),
                    ("sioe", "SIOE+"),
                    ("ep", "Parlamento Europeu"),
                    ("nipc", "NIPC"),
                    ("lei", "LEI (GLEIF)"),
                    ("eu_tr", "Registo de Transparência da UE"),
                    ("ec", "Comissão Europeia"),
                    ("wikidata", "Wikidata (pista)"),
                    ("declared_name", "Organização sem identificador (nome declarado)"),
                    ("scoped_name", "Pessoa sem identificador (nome na fonte)"),
                ],
                max_length=16,
                verbose_name="esquema",
            ),
        ),
        migrations.AlterField(
            model_name="sourceobservation",
            name="kind",
            field=models.CharField(
                blank=True,
                choices=[
                    ("employment", "Emprego"),
                    ("directorship", "Administração"),
                    ("shareholding", "Participação societária"),
                    ("membership", "Filiação"),
                    ("education", "Formação"),
                    ("family", "Relação familiar"),
                    ("public_office", "Cargo público"),
                    ("professional_activity", "Atividade profissional"),
                    ("part_of", "Integra"),
                    ("succession", "Sucede a"),
                    ("declared_client", "Cliente declarado"),
                ],
                max_length=24,
                verbose_name="tipo indicado pela fonte",
            ),
        ),
        migrations.CreateModel(
            name="EntityAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=300, verbose_name="nome")),
                (
                    "normalised",
                    models.CharField(
                        db_index=True, max_length=300, verbose_name="nome normalizado"
                    ),
                ),
                (
                    "scheme",
                    models.CharField(
                        choices=[
                            ("government", "Governo"),
                            ("ept", "Entidade para a Transparência"),
                            ("parliament", "Assembleia da República"),
                            ("sioe", "SIOE+"),
                            ("ep", "Parlamento Europeu"),
                            ("nipc", "NIPC"),
                            ("lei", "LEI (GLEIF)"),
                            ("eu_tr", "Registo de Transparência da UE"),
                            ("ec", "Comissão Europeia"),
                            ("wikidata", "Wikidata (pista)"),
                            ("declared_name", "Organização sem identificador (nome declarado)"),
                            ("scoped_name", "Pessoa sem identificador (nome na fonte)"),
                        ],
                        max_length=16,
                        verbose_name="esquema",
                    ),
                ),
                (
                    "external_id",
                    models.CharField(max_length=240, verbose_name="identificador oficial"),
                ),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "verbose_name": "nome alternativo",
                "verbose_name_plural": "nomes alternativos",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("entity", "normalised", "scheme", "external_id"),
                        name="entity_alias_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ParliamentStatusInterval",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("cadastro_id", models.CharField(db_index=True, max_length=20)),
                ("legislature", models.CharField(max_length=12)),
                ("status", models.CharField(max_length=80, verbose_name="situação publicada")),
                ("start", models.DateField()),
                ("end", models.DateField(blank=True, null=True)),
                (
                    "entity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parliament_status_intervals",
                        to="core.entity",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(fields=["status", "start"], name="parliament_status_start_idx")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("cadastro_id", "legislature", "status", "start"),
                        name="parliament_status_interval_unique",
                    )
                ],
            },
        ),
    ]
