"""Generate local-only credentials without reading or overwriting an existing environment."""

import os
import secrets
from pathlib import Path


def main() -> None:
    target = Path(__file__).resolve().parents[1] / ".env"
    if target.is_symlink():
        raise SystemExit("Refusing a symlink at .env.")
    if target.exists():
        if not target.is_file():
            raise SystemExit(".env must be a regular file.")
        target.chmod(0o600)
        print("Existing .env retained; permissions set to 0600.")
        return
    password = secrets.token_hex(32)
    secret = secrets.token_urlsafe(64)
    content = (
        "# Local development only; generated by scripts/dev-env.py.\n"
        "DJANGO_SETTINGS_MODULE=config.settings.development\n"
        f"SECRET_KEY={secret}\n"
        "ALLOWED_HOSTS=localhost,127.0.0.1\n"
        "CSRF_TRUSTED_ORIGINS=http://localhost:8000,http://127.0.0.1:8000\n"
        "ENABLE_ADMIN=true\n"
        f"POSTGRES_PASSWORD={password}\n"
        f"DATABASE_URL=postgresql://pt_ligacoes:{password}@127.0.0.1:5432/pt_ligacoes\n"
        f"E2E_DATABASE_URL=postgresql://pt_ligacoes:{password}@127.0.0.1:5432/pt_ligacoes_e2e\n"
    )
    descriptor = os.open(target, os.O_WRONLY | os.O_CREAT | os.O_EXCL, 0o600)
    with os.fdopen(descriptor, "w") as output:
        output.write(content)
    print("Created local .env with random credentials and permissions 0600.")


if __name__ == "__main__":
    main()
